### ISSUE TITLE
For Products, New Field to split Courses into two categories "One Demand" or "Synchronous"

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#103]
![screen shot 2016-03-10 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/17462907/13684870/606b83aa-e6d3-11e5-98f9-6da799211447.png)

**Comment by bikash02** [comment]
updated the new field and I set the option for the first product.Kindly check the below link.
http://progressiverenewal.org/product-category/online-courses/

**Comment by thomaskleczka** [comment]
Looks great.  Thank you Bikash!
