### ISSUE TITLE
Text in course, webinars, etc showing up as search query results.

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#108]
additionally, Where is the input field to change that image in the WP back end?

![screen shot 2016-04-08 at 9 02 49 am](https://cloud.githubusercontent.com/assets/17462907/14386025/b9fde470-fd68-11e5-8559-cbcea8da9924.png)

**Comment by debdiproy** [comment]
Need intimidate attention

**Comment by bikash02** [comment]
Steps to follow for changing the image from WP backend
1.Edit the product.
2.Remove the Product image from the right hand side and set the new one.
3.Click on "Update" button.

**Comment by bikash02** [comment]
Updated the title that showing up as search query..

**Comment by thomaskleczka** [comment]
Will that change the product image only or ill it change the large black bar with the white text in it displaying across the top of the page?

**Comment by bikash02** [comment]
At this time you only able to change the product image.
If you would like to change the top bar image then we have to make it dynamic.
Please let me know your feedback.

**Comment by thomaskleczka** [comment]
Sorry for the delay on this issue.  I would like to have that be dynamic that we can add an image into that black bar with the text,  Thank you
Thomas

**Comment by bikash02** [comment]
updated the code.
Input field name in the page: Top Bar Image

**Comment by thomaskleczka** [comment]
@bikash02 Thank you for updating this.  I see the input field for all the pages. and have tested it, and it works.  Do you know the sizes for images to place in these fields?
Additionally,  I do not see this field while editing products.  ON the page for each product, the black bar is gone, and the text is white, and you can't see the course title..  Can you add that field for when I am editing courses as well please?  
@debdiproy @camerontrimble

**Comment by bikash02** [comment]
I have updated the top image for the product as well.Kindly check once again.

**Comment by thomaskleczka** [comment]
Perfect @bikash02 Thank you!
-Thomas
