### ISSUE TITLE
Add Image to Main Page Hero Slider

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#110]
Please add this image to the front page slider.  Please have it be the first image that appears.
Thank you

![nclicprheroimage-01](https://cloud.githubusercontent.com/assets/17462907/14709815/3b4171d0-0798-11e6-837d-f550e2321c9a.png)

!
Thomas.

**Comment by bikash02** [comment]
Can you please send me the image without text?
The current image was not fit to the slider or you can send me the psd also if you have.
Thank you.

**Comment by thomaskleczka** [comment]
Sent .PSD file through email.
Thomas.

**Comment by bikash02** [comment]
updated the slider image.
