### ISSUE TITLE
ASAP: Change "Read More" and "Add to Cart" buttons on Confrences page on PreogressiveRenewal.org

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#111]
Hi Team.
Please change the hyper links on this page http://progressiverenewal.org/conferences/
for the product listed at National Church Leadership institute.
The Button "READ MORE" should link to www.NCLI16.or
and the Add to cart button, cane we change the text to "Register Now" and have it link to https://www.eventbrite.com/e/national-church-leadership-institute-2016-tickets-21463529996

**Comment by bikash02** [comment]
updated..

**Comment by thomaskleczka** [comment]
Thank yoU!
