### ISSUE TITLE
On Demand Editable Field for Courses

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#112]
Hi Team.
A few weeks ago you created the field for "on demand vs synchronous" for courses.  Could we please change that from an option based field with only two choices, to an Input based field, where I'll be able to type information such as specific dates in or the words On Demand.
Thank you.
@camerontrimble @debdiproy

**Comment by bikash02** [comment]
updated

**Comment by thomaskleczka** [comment]
Works Perfectly.  Thank you!
Tk
