### ISSUE TITLE
We need to be able to edit a product in the VISUAL tab. Right now we can only edit in the TEXT tab.

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#113]

**Comment by bikash02** [comment]
Please click on the "Visual" tab for editing the page in visual mode.
I have updated some plugins and its working for me.
If you are still getting the same error then we have to update the wordpress core files.
Leave your status please.
**Before updating the core files we have to keep a backup for the full website.**

**Comment by camerontrimble** [comment]
Now we can only edit in the Visual tab and we can't add any media files or forms to the description.

**Comment by camerontrimble** [comment]
Issue resolved as I said it was created by a plugin called woocommerce subscription. Simply disable it before adding media and the re-nable after completion of editing.
