### ISSUE TITLE
Add Media Button Not working on "Short Description" for products.

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#114]
The "Add Media" button is not working on "Short Description" for products.  I am not able to add video to the product description.  Is this a bug or a limit of the functionality? 
Thank you.
Thomas.

**Comment by bikash02** [comment]
I have check the WP backend and I thought It was happened due to conflict some other problematic plugin.The Editor was working fine for the web pages.

**Comment by thomaskleczka** [comment]
Yes the editor does work fine for "Web Pages" and allows me to add media, but for products, it won't allow me to add the media.  Is this a limit of the plugin or a bug?  Is there another solution?
Thank you,
Thomas

**Comment by bikash02** [comment]
It’s not the limitation of Plugin.We try to find out the solution.

**Comment by camerontrimble** [comment]
Issue resolved as I said it was created by a plugin called woocommerce subscription. Simply disable it before adding media and the re-nable after completion of editing.
