### ISSUE TITLE
Change Title of Icons on /webinars page 

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#115]
Hi Team.
Could we please change 2 titles for the icons on http://progressiverenewal.org/webinars/

Current - Sales - Please change to "Leading Congregations to Change"
Current - Leading Congregations to Change - Please change to "Social Justice"

Thank you.
@debdiproy @camerontrimble

**Comment by bikash02** [comment]
updated the titles.
