### ISSUE TITLE
Widget on Front page of PR.org

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#116]
How do I edit the text in this widget Next tot he hands shaking?  Is it dynamic or do I pass the text edits onto you?
![screen shot 2016-05-26 at 12 25 22 pm](https://cloud.githubusercontent.com/assets/17462907/15583820/10c0d750-233d-11e6-9773-1cb9060ceea1.png)
@debdiproy @camerontrimble

**Comment by bikash02** [comment]
Don't worry I will make it dynamic.

**Comment by bikash02** [comment]
I have updated the home page template and make the below section dynamic.
1.Four Boxes below the slider
2.Church Planting banner image
3.Featured services.

Let me know if there anything else I can help you.

**Comment by thomaskleczka** [comment]
Hi @bikash02 Thank you for updating those elements.  I appreciate it very much.  The one elemenet though that I really needed dynamic still seems to be not able to update.  it's the one from the picture I posted, Member Services.  specifically the tab for "Member benefits"  Thank you!
Thomas.

**Comment by bikash02** [comment]
I have updated the template.

**Comment by thomaskleczka** [comment]
this is brilliant!  Thanks @bikash02 You're the best!

**Comment by bikash02** [comment]
You welcome @thomaskleczka.Please let me know if I can be of any help.
