### ISSUE TITLE
Load code in place of form (5): speaker

### ISSUE THREAD

**Issue by marleewalters** [ProgressiveRenewal/progress16#125]
Please load this code in place of form on the following page:
http://progressiverenewal.org/reserve-a-speaker/

Javascript:

<script type="text/javascript"  #src="https://qd994.infusionsoft.com/app/form/iframe/ead02291b3ebbe5d4b7f173a5b51d8cd"></script>

HTML:
<style type="text/css">
.beta-base .preheader, .beta-base .header, .beta-base .sidebar, .beta-base .body, .beta-base .footer, #mainContent {
    text-align: left;
}
.beta-base .preheader, .beta-base .header, .beta-base .body, .beta-base .sidebar, .beta-base .leftSidebar, .beta-base .rightSidebar, .beta-base .footer {
    margin: 0;
    padding: 0;
    border: none;
    white-space: normal;
    line-height: normal;
}
.beta-base .title, .beta-base .subtitle, .beta-base .text, .beta-base img {
    margin: 0;
    padding: 0;
    background: none;
    border: none;
    white-space: normal;
    line-height: normal;
}
.beta-base .bodyContainer td.preheader{
    padding: 10px 0;
}
.beta-base .bodyContainer td.header {
    padding: 0;
    height: 30px;
}
.beta-base .bodyContainer td.body, .beta-base .bodyContainer td.footer,
.beta-base .bodyContainer td.sidebar, .beta-base .bodyContainer td.leftSidebar, .beta-base .bodyContainer td.rightSidebar {
    padding: 20px;
}
.beta-base .bodyContainer td.header p, .beta-base .bodyContainer td.preheader p, .beta-base .bodyContainer td.body p,
.beta-base .bodyContainer td.footer p, .beta-base .bodyContainer td.sidebar p,
.beta-base .bodyContainer td.leftSidebar p, .beta-base .bodyContainer td.rightSidebar p {
    margin: 0;
    color: inherit;
}
.beta-base .bodyContainer td.header div.title, .beta-base .bodyContainer td.preheader div.title, .beta-base .bodyContainer td.body div.title,
.beta-base .bodyContainer td.footer div.title, .beta-base .bodyContainer td.sidebar div.title,
.beta-base .bodyContainer td.leftSidebar div.title, .beta-base .bodyContainer td.rightSidebar div.title,
.beta-base .bodyContainer td.header div.subtitle, .beta-base .bodyContainer td.preheader div.subtitle, .beta-base .bodyContainer td.body div.subtitle,
.beta-base .bodyContainer td.footer div.subtitle, .beta-base .bodyContainer td.sidebar div.subtitle,
.beta-base .bodyContainer td.leftSidebar div.subtitle, .beta-base .bodyContainer td.rightSidebar div.subtitle,
.beta-base .bodyContainer td.header div.text, .beta-base .bodyContainer td.preheader div.text, .beta-base .bodyContainer td.body div.text, .beta-base .bodyContainer td.body div.text div,
.beta-base .bodyContainer td.footer div.text, .beta-base .bodyContainer td.sidebar div.text,
.beta-base .bodyContainer td.leftSidebar div.text, .beta-base .bodyContainer td.rightSidebar div.text {
    overflow: auto;
}
.beta-base .optout {
    margin-bottom: 10px;
    margin-top: 10px;
}
div.infusion-captcha {
    width: 220px;
    padding: 10px;
}
div.infusion-captcha input, div.infusion-captcha select, div.infusion-captcha textarea {
    width: 95%;
    display: inline-block;
    vertical-align: middle;
}
table.infusion-field-container td.infusion-field-input-container input[type='text'],
table.infusion-field-container td.infusion-field-input-container input[type='password'],
table.infusion-field-container td.infusion-field-input-container textarea {
    width: 98%; /* must be 98% to make the snippet-menu line up due to border width */
    margin: 0;
}
table.infusion-field-container td.infusion-field-input-container select {
    width: 101%;
    *width: 102%; /* this one for IE */
    margin: 0;
}
table.infusion-field-container td.infusion-field-label-container {
    padding-right: 5px;
}
td.header .image-snippet img {
    vertical-align: bottom;
}
#webformErrors {
    color: #990000;
    font-size: 14px;
}
html, body {
    margin: 0;
    padding: 0;
    height: 100%;
}
.infusion-form {
    margin: 0;
    height: 100%;
}
.infusion-option {
    display: block;
    text-align: left;
}
</style>
<style type="text/css">
.beta-font-b h1, .beta-font-b h2, .beta-font-b h3, .beta-font-b h4, .beta-font-b h5, .beta-font-b h6 {
    font-family: arial,sans-serif;
}
.beta-font-b h1 {font-size: 24px;}
.beta-font-b h2 {font-size: 20px;}
.beta-font-b h3 {font-size: 14px;}
.beta-font-b h4 {font-size: 12px;}
.beta-font-b h5 {font-size: 10px;}
.beta-font-b h6 {font-size: 8px;}
.beta-font-b address {font-style: italic;}
.beta-font-b pre {font-family: Courier New, monospace;}
.beta-font-b .title, .beta-font-b .title p {
    font-size: 20px;
    font-weight: bold;
    font-family: arial,sans-serif;
}
.beta-font-b .subtitle, .beta-font-b .subtitle p {
    font-size: 11px;
    font-weight: normal;
    font-family: arial,sans-serif;
}
.beta-font-b .text, .beta-font-b p {
    font-size: 12px;
    font-family: arial,sans-serif;
}
.beta-font-b .preheader .text, .beta-font-b .preheader .text p {
    font-size: 11px;
    font-family: arial,sans-serif;
}
.beta-font-b .footer a {
    font-size: 11px;
    font-family: arial,sans-serif;
}
.beta-font-b .footer .text {
    font-size: 10px;
    font-family: verdana,sans-serif;
}
.beta-font-b .sidebar .title, .beta-font-b .leftSidebar .title, .beta-font-b .rightSidebar .title {
    font-size: 15px;
    font-weight: bold;
    font-family: arial,sans-serif;
}
.beta-font-b .sidebar .subtitle, .beta-font-b .leftSidebar .subtitle, .beta-font-b .rightSidebar .subtitle {
    font-size: 12px;
    font-family: arial, sans-serif;
}
.beta-font-b .sidebar .text, .beta-font-b .sidebar .text p, .beta-font-b .leftSidebar .text, .beta-font-b .rightSidebar .text {
    font-size: 11px;
    font-family: arial, sans-serif;
}
.infusion-field-label-container {
    font-size: 14px;
    font-family: arial,sans-serif;
}
.infusion-field-input-container {
    color: #000000;
    font-size: 12px;
}
.infusion-option label {
    color: #000000;
    font-size: 14px;
    font-family: arial,sans-serif;
}
</style>
<style type="text/css">
.custom-34 .background{
background-color:#ffffff;
;
}
.custom-34 .title{
color:#1a242e;
;
}
.custom-34 .subtitle{
color:#000000;
;
}
.custom-34 .text{
color:#000000;
;
}
.custom-34 a{
color:#0645ad;
;
}
.custom-34 .background .preheader .text{
color:#1a242e;
;
}
.custom-34 .background .preheader a{
color:#0645ad;
;
}
.custom-34 .header{
background-color:#ffffff;
;
}
.custom-34 .header .title{
color:#000000;
;
}
.custom-34 .header .subtitle{
color:#000000;
;
}
.custom-34 .header .text{
color:#000000;
;
}
.custom-34 .header .a{
color:#157DB8;
;
}
.custom-34 .hero{
background-color:#025C8D;
;
}
.custom-34 .hero .title{
color:#FFFFFF;
;
}
.custom-34 .hero .subtitle{
color:#FFFFFF;
;
}
.custom-34 .hero .text{
color:#FFFFFF;
;
}
.custom-34 .hero .a{
color:#157DB8;
;
}
.custom-34 .quote{
background-color:#013B5A;
;
}
.custom-34 .quote:after{
border-color:#013B5A transparent transparent transparent;
;
}
.custom-34 .quote .title{
color:#FFFFFF;
;
}
.custom-34 .quote .subtitle{
color:#FFFFFF;
;
}
.custom-34 .quote .text{
color:#FFFFFF;
;
}
.custom-34 .quote .a{
color:#157DB8;
;
}
.custom-34 .body{
background-color:#ffffff;
;
}
.custom-34 .main .title{
color:#000000;
;
}
.custom-34 .main .subtitle{
color:#000000;
;
}
.custom-34 .main .text{
color:#000000;
;
}
.custom-34 .main .a{
color:#157DB8;
;
}
.custom-34 .sidebar{
background-color:#ffffff;
;
}
.custom-34 .sidebar .title{
color:#000000;
;
}
.custom-34 .sidebar .subtitle{
color:#000000;
;
}
.custom-34 .sidebar .text{
color:#000000;
;
}
.custom-34 .sidebar .a{
color:#157DB8;
;
}
.custom-34 .leftSidebar{
background-color:#ffffff;
;
}
.custom-34 .leftSidebar .title{
color:#000000;
;
}
.custom-34 .leftSidebar .subtitle{
color:#000000;
;
}
.custom-34 .rightSidebar{
background-color:#ffffff;
;
}
.custom-34 .rightSidebar .title{
color:#000000;
;
}
.custom-34 .rightSidebar .subtitle{
color:#000000;
;
}
.custom-34 .footer{
background-color:#ffffff;
;
}
.custom-34 .footer .text{
color:#000000;
;
}
.custom-34 .footer .title{
color:#000000;
;
}
.custom-34 .footer a{
color:#0645ad;
;
}
.custom-34 .footer .subtitle{
color:#000000;
;
}
.custom-34 .infusion-field-label-container{
font-size:12px;
;
}
.custom-34 .infusion-field-label-container{
font-family:Arial;
;
}
.custom-34 .infusion-field-label-container{
color:#000000;
;
}
.custom-34 .infusion-field-input{
font-size:14px;
;
}
.custom-34 .infusion-option label{
font-size:12px;
;
}
.custom-34 .infusion-option label{
font-family:Arial;
;
}
.custom-34 .infusion-option label{
color:#000000;
;
}
.custom-34 .webFormBodyContainer{
border-width:1px;
;
}
.custom-34 .webFormBodyContainer{
border-style:Solid;
;
}
.custom-34 .webFormBodyContainer{
border-color:#000000;
;
}
</style>
<style type="text/css">
.infusion-field-label-container {
text-align:Left;
}
.infusion-field-input-container {
width:200px;
}
.infusion-field-label-container {
vertical-align:Middle;
}
.bodyContainer {
width:425px;
}
</style>
<script src="https://qd994.infusionsoft.com/app/webTracking/getTrackingCode?trackingId=db214e5f8c55b90d20cc77b3d4b2b0a3&b=1.56.0.49" type="text/javascript">
</script>
<div class="text" id="webformErrors" name="errorContent">
</div>
<form accept-charset="UTF-8" action="https://qd994.infusionsoft.com/app/form/process/ead02291b3ebbe5d4b7f173a5b51d8cd" class="infusion-form" method="POST" name="Speaker Inquiry" onsubmit="var form = document.forms[0];
var resolution = document.createElement('input');
resolution.setAttribute('id', 'screenResolution');
resolution.setAttribute('type', 'hidden');
resolution.setAttribute('name', 'screenResolution');
var resolutionString = screen.width + 'x' + screen.height;
resolution.setAttribute('value', resolutionString);
form.appendChild(resolution);
var pluginString = '';
if (window.ActiveXObject) {
    var activeXNames = {'AcroPDF.PDF':'Adobe Reader',
        'ShockwaveFlash.ShockwaveFlash':'Flash',
        'QuickTime.QuickTime':'Quick Time',
        'SWCtl':'Shockwave',
        'WMPLayer.OCX':'Windows Media Player',
        'AgControl.AgControl':'Silverlight'};
    var plugin = null;
    for (var activeKey in activeXNames) {
        try {
            plugin = null;
            plugin = new ActiveXObject(activeKey);
        } catch (e) {
            // do nothing, the plugin is not installed
        }
        pluginString += activeXNames[activeKey] + ',';
    }
    var realPlayerNames = ['rmockx.RealPlayer G2 Control',
        'rmocx.RealPlayer G2 Control.1',
        'RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)',
        'RealVideo.RealVideo(tm) ActiveX Control (32-bit)',
        'RealPlayer'];
    for (var index = 0; index &lt; realPlayerNames.length; index++) {
        try {
            plugin = new ActiveXObject(realPlayerNames[index]);
        } catch (e) {
            continue;
        }
        if (plugin) {
            break;
        }
    }
    if (plugin) {
        pluginString += 'RealPlayer,';
    }
} else {
    for (var i = 0; i &lt; navigator.plugins.length; i++) {
        pluginString += navigator.plugins[i].name + ',';
    }
}
pluginString = pluginString.substring(0, pluginString.lastIndexOf(','));
var plugins = document.createElement('input');
plugins.setAttribute('id', 'pluginList');
plugins.setAttribute('type', 'hidden');
plugins.setAttribute('name', 'pluginList');
plugins.setAttribute('value', pluginString);
form.appendChild(plugins);
var java = navigator.javaEnabled();
var javaEnabled = document.createElement('input');
javaEnabled.setAttribute('id', 'javaEnabled');
javaEnabled.setAttribute('type', 'hidden');
javaEnabled.setAttribute('name', 'javaEnabled');
javaEnabled.setAttribute('value', java);
form.appendChild(javaEnabled);">
<input name="inf_form_xid" type="hidden" value="ead02291b3ebbe5d4b7f173a5b51d8cd" /><input name="inf_form_name" type="hidden" value="Speaker Inquiry" /><input name="infusionsoft_version" type="hidden" value="1.56.0.49" />
<div class="custom-34 beta-base beta-font-b" id="mainContent" style="height:100%">
<table cellpadding="10" cellspacing="0" class="background" style="width: 100%; height: 100%">
<tbody>
<tr>
<td align="center" valign="top">
<table bgcolor="#FFFFFF" cellpadding="20" cellspacing="0" class="bodyContainer webFormBodyContainer" width="100%">
<tbody>
<tr>
<td bgcolor="#FFFFFF" class="body" sectionid="body" valign="top">
<div>
<div>
<div class="title" style="text-align:left">
<div class="title" contentid="title" style="text-align: left;">
<div>
Request a Speaker
</div>
</div>
</div>
</div>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_FirstName">First Name *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_FirstName" name="inf_field_FirstName" type="text" />
</td>
</tr>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_LastName">Last Name *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_LastName" name="inf_field_LastName" type="text" />
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_Email">Email *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_Email" name="inf_field_Email" type="text" />
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_StreetAddress1">Street Address 1 *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_StreetAddress1" name="inf_field_StreetAddress1" type="text" />
</td>
</tr>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_StreetAddress2">Street Address 2</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_StreetAddress2" name="inf_field_StreetAddress2" type="text" />
</td>
</tr>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_City">City *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_City" name="inf_field_City" type="text" />
</td>
</tr>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_State">State *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_State" name="inf_field_State" type="text" />
</td>
</tr>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_PostalCode">Postal Code *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_PostalCode" name="inf_field_PostalCode" type="text" />
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_Phone1">Phone *</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_Phone1" name="inf_field_Phone1" type="text" />
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_Company">Church Name</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_Company" name="inf_field_Company" type="text" />
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_field_Website">Church Website</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<input class="infusion-field-input-container" id="inf_field_Website" name="inf_field_Website" type="text" />
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label class="infusion-field-label-container" for="inf_option_SpeakerTopic">Speaker Topic</label>
</td><td class="infusion-field-input-container" style="width:200px;">
<div class="infusion-radio">
<span class="infusion-option"><input id="inf_option_SpeakerTopic_5955" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5955" /><label for="inf_option_SpeakerTopic_5955">Asset Mapping</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5957" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5957" /><label for="inf_option_SpeakerTopic_5957">Church Planting</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5963" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5963" /><label for="inf_option_SpeakerTopic_5963">Church Renewal</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5961" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5961" /><label for="inf_option_SpeakerTopic_5961">Community Organizing</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5959" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5959" /><label for="inf_option_SpeakerTopic_5959">Conflict Resolution</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5971" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5971" /><label for="inf_option_SpeakerTopic_5971">Denominational Best Practices and Trends</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5969" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5969" /><label for="inf_option_SpeakerTopic_5969">Future of the Church</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5967" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5967" /><label for="inf_option_SpeakerTopic_5967">Leadership</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5979" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5979" /><label for="inf_option_SpeakerTopic_5979">Money and Stewardship</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5977" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5977" /><label for="inf_option_SpeakerTopic_5977">Organizational Development</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5975" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5975" /><label for="inf_option_SpeakerTopic_5975">Pastoral Care</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5973" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5973" /><label for="inf_option_SpeakerTopic_5973">Social Media/Communication</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5983" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5983" /><label for="inf_option_SpeakerTopic_5983">Strategic Planning</label></span><span class="infusion-option"><input id="inf_option_SpeakerTopic_5981" name="inf_option_SpeakerTopic" style="margin-right:3px;" type="radio" value="5981" /><label for="inf_option_SpeakerTopic_5981">Transformational Worship</label></span>
</div>
</td>
</tr>
</tbody>
</table>
</div>
<div>
<table class="infusion-field-container" style="width:100%;">
<tbody>
<tr>
<td class="infusion-field-label-container">
<label for="inf_custom_BriefDescriptionofYourChurchandSetting">Anything else we need to know?</label>
</td>
<td class="infusion-field-input-container" style="width:200px;">
<textarea cols="24" id="inf_custom_BriefDescriptionofYourChurchandSetting" name="inf_custom_BriefDescriptionofYourChurchandSetting" rows="5"></textarea>
</td>
</tr>
</tbody>
</table>
</div>
<div>
<div style="height:15px; line-height:15px;">
&nbsp;
</div>
</div>
<div>
<div class="infusion-submit" style="text-align:left;">
<button style="" type="submit" value="Submit">Submit</button>
</div>
</div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</form>

**Comment by camerontrimble** [comment]
Completed
