### ISSUE TITLE
Condense Instructors page to one page

### ISSUE THREAD

**Issue by marleewalters** [ProgressiveRenewal/progress16#127]
The Instructors page (http://progressiverenewal.org/instructors/) is the only one with photos and bios of people that goes onto two pages. Can they all fit onto one page?
![instructors](https://cloud.githubusercontent.com/assets/20711891/17280137/958cfe26-5756-11e6-9dd2-c468a0c51bca.png)

**Comment by debdiproy** [comment]
Completed
