### ISSUE TITLE
Classroom page not loading correctly

### ISSUE THREAD

**Issue by marleewalters** [ProgressiveRenewal/progress16#128]
Could you take a look at the Classroom page (http://progressiverenewal.org/classroom/)? It isn't loading correctly.
![classroom](https://cloud.githubusercontent.com/assets/20711891/17280155/16a24b88-5757-11e6-9d81-1d4139bd4260.png)

**Comment by Designer-cleonix** [comment]
We have to re-build this page. Please provide us the content.

**Comment by camerontrimble** [comment]
Link to: https://cpr.instructure.com/login/canvas

**Comment by bikash02** [comment]
updated
