### ISSUE TITLE
Leadership Team page http://progressiverenewal.org/about/leadership-staff/ edits

### ISSUE THREAD

**Issue by marleewalters** [ProgressiveRenewal/progress16#129]
Why doesn't Lindsay's bio have a "read more" link on it like everyone else's? (see attached)
![screen shot 2016-08-02 at 2 22 31 pm](https://cloud.githubusercontent.com/assets/20711891/17340097/d14b0824-58bc-11e6-88ab-1091d07a9193.png)

How can I edit the contact widgets under each person's profile? Some are no accurate and some do not have any. (see attached)
![screen shot 2016-08-02 at 2 22 46 pm](https://cloud.githubusercontent.com/assets/20711891/17340106/d6df9480-58bc-11e6-9445-e38deca25a0b.png)

How are people sorted on this page? Could we change the sorting to a custom/alphabetical sort?

**Comment by bikash02** [comment]
I have fixed the issue.
Please follow the below steps
1.Login the WP admin
2.Click on http://progressiverenewal.org/about/leadership-staff/
3.Next click to "read more" and you will find "Edit Team Member" top of the main menu.
4.Update the content for the member and Click on "Update"

**Comment by bikash02** [comment]
You can set the sorting order like 1.Date,2.ID,3.Name,4.Random Order,5.Title

**Comment by marleewalters** [comment]
That edits the content of their bio, but not the contact widgets.

Could we set the sorting to be 1. Last Name?

**Comment by bikash02** [comment]
You can update the contact info like address and social information under the editor.
Only the above five options are available.

**Comment by bikash02** [comment]
Would you like to edit Categories,Latest Posts in the right side widgets?
