### ISSUE TITLE
This is for the RTE website theoedu.org

### ISSUE THREAD

**Issue by marleewalters** [ProgressiveRenewal/progress16#132]
From Jeremy:

For the videos, I'd like one of two things:  1) for the embedded player to be sized such that I can place two side-by-side on a full width page (and without creating extra white space around the player).  I can do this with a 3rd party plug in now, but not the plug-in that comes with the theme.  Or 2) a half-page width embedded player on one side with a text box to the other side where I can write a description of the video.

**Comment by debdiproy** [comment]
Send us the login information for the project

**Comment by marleewalters** [comment]
http://theoedu.org/wp-admin
username: adminjf
password: @Monday@Tuesday/2001

Marlee Walters

Associate Pastor of Operations
Forefront Church
79 Madison Ave
New York, NY 10016
forefrontnyc.com

**Comment by bikash02** [comment]
I have cloned the page and updated the page structure.
http://www.theoedu.org/test/
Please let me know if anything else you need.

**Comment by bikash02** [comment]
Once you have approved I'll do the changes in live page.

**Comment by marleewalters** [comment]
Go ahead and make live. Thank you,

Marlee Walters

Associate Pastor of Operations
Forefront Church
79 Madison Ave
New York, NY 10016
forefrontnyc.com

**Comment by bikash02** [comment]
Updated.Here is the link http://www.theoedu.org/summit-meetings/summit-media/
Please update the videos description.

**Comment by bikash02** [comment]
Please close the issue if resolved.
