### ISSUE TITLE
Add Holly Roach to the list of instructors for online courses

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#133]
Please connect ASAP. @debdiproy

**Comment by bikash02** [comment]
She already added to the list.
http://progressiverenewal.org/instructors/

**Comment by thomaskleczka** [comment]
Sorry for not being clearer: I mean  where you add the attributes to each product and define who is the instructor for the course.

![screen shot 2016-09-09 at 9 24 07 am](https://cloud.githubusercontent.com/assets/17462907/18390315/53483430-766f-11e6-96ca-fc472436e09a.png)

**Comment by bikash02** [comment]
updated.

**Comment by bikash02** [comment]
Anything else you want to add to the instructor list?

**Comment by thomaskleczka** [comment]
No thank you.  Thanks for Handling this!
