### ISSUE TITLE
pictures are failing to upload for setting product images

### ISSUE THREAD

**Issue by thomaskleczka** [ProgressiveRenewal/progress16#134]
Every time i try to upload an image to a product, it fails.  Please check ASAP. @debdiproy

**Comment by bikash02** [comment]
Can you please tell me the product name?

**Comment by thomaskleczka** [comment]
Dismantling Racism

**Comment by bikash02** [comment]
Please provide me the product image.

**Comment by thomaskleczka** [comment]
![screen shot 2016-09-08 at 9 49 53 pm](https://cloud.githubusercontent.com/assets/17462907/18390374/93404596-766f-11e6-99e2-820550d04719.png)

**Comment by bikash02** [comment]
Thank you so much.I will update you after few minutes.

**Comment by bikash02** [comment]
Please unlock the product.I'm not able to update or preview the product.

**Comment by thomaskleczka** [comment]
I have left the product edit window.  will that unlock it for you now?

**Comment by bikash02** [comment]
yes thank you.

**Comment by bikash02** [comment]
updated
