### ISSUE TITLE
Please replace logo on FundThisMinistry.org

### ISSUE THREAD

**Issue by marleewalters** [ProgressiveRenewal/progress16#136]
Please replace the current logo with this
![fund this ministry logo](https://cloud.githubusercontent.com/assets/20711891/18558896/ebe81df4-7b42-11e6-9518-fb8a7b4cb36a.png)
on fundthisministry.org website, all pages

**Comment by bikash02** [comment]
@i-puspita Please resize the logo according to the website layout and send it to me.I need two logos, one for header and one for footer.

**Comment by bikash02** [comment]
updated

**Comment by marleewalters** [comment]
What sizeis that?

Marlee Walters

Associate Pastor of Operations
Forefront Church
79 Madison Ave
New York, NY 10016
forefrontnyc.com

**Comment by bikash02** [comment]
Header logo:  218X41
Footer logo:  200X41

**Comment by bikash02** [comment]
If you have the .psd file please send it to us and we'll fix it.

**Comment by bikash02** [comment]
is it okay?
