### ISSUE TITLE
Move over pages from http://progressiverenewal.org/new-congregational-development-age-narrowcasting-highlights/

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#18]

**Comment by debdiproy** [comment]
Please copy pages inside this page all the right hand site links and boxes please check

**Comment by bikash02** [comment]
Copied all the pages..
note:http://progress16.staging.wpengine.com/new-congregational-development-age-narrowcasting-highlights/ncd-kind-new-churches/ having some js/plugin issues.
Parent link:the page is displaying some js code.
http://progressiverenewal.org/new-congregational-development-age-narrowcasting-highlights/ncd-kind-new-churches/

**Comment by camerontrimble** [comment]
These pages need a side navigation menu to navigate within the section. See the main page for the the navigation links: http://progress16.staging.wpengine.com/new-congregational-development-age-narrowcasting-highlights/

**Comment by bikash02** [comment]
Added the side navigation to all the respective pages..
