### ISSUE TITLE
Please link "Contact Us" boxes on homepage sliders

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#42]
Change button to say "Find Out More"

Brian McLaren slide: http://progress16.staging.wpengine.com/contacts/
Yvette Flunder Slide: http://progress16.staging.wpengine.com/start-a-new-church/coaching/
Bruce Reyes Chow Slide: http://progress16.staging.wpengine.com/denomination/consulting-2/
John Dorhauer Slide: http://progress16.staging.wpengine.com/denomination/
Cameron Trimble Slide: http://progress16.staging.wpengine.com/revitalize-your-church/ways-can-help/

![screenshot 2016-01-13 14 41 30](https://cloud.githubusercontent.com/assets/15096099/12305742/49d1ad8c-ba04-11e5-8bdd-de372a42502b.png)

**Comment by bikash02** [comment]
updated homepage sliders
