### ISSUE TITLE
Install Job Search plugin

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#46]
Talked to Debdip about this feature.

**Comment by bikash02** [comment]
I have installed the job manager plugin.Kindly check the below pages.
http://progress16.staging.wpengine.com/jobs/
http://progress16.staging.wpengine.com/job-dashboard/
http://progress16.staging.wpengine.com/post-a-job/

**Comment by camerontrimble** [comment]
Connect http://progress16.staging.wpengine.com/jobs/ to top navigation under New Church and Revitalize

**Comment by bikash02** [comment]
updated the top menu.kindly check.
