### ISSUE TITLE
Format Collaborations page

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#51]
http://progress16.staging.wpengine.com/collaborations/

**Add these Collaborations:**

Agile Church - Grab info off the website

Auburn Seminary - Leaders of faith and moral courage have guided social change throughout our nation’s history—from the abolition of slavery and the fight for Civil Rights to the struggle against gun violence and global warming. Auburn identifies and strengthens leaders—from the pulpit to the public square—to build communities, bridge divides, pursue justice, and heal the world.
![auburn](https://cloud.githubusercontent.com/assets/15096099/12699312/0c4ad432-c785-11e5-94f0-9744b8f095e8.gif)

Franciscan Action Network - We are a grassroots organization amplifying the justice efforts of Franciscans and Franciscan-hearted people around the country. Join our growing movement that endures from St. Francis of Assisi and his call for compassion for the poor and for creation over 800 years ago.
![fanlogo](https://cloud.githubusercontent.com/assets/15096099/12699326/5d801b6e-c785-11e5-9028-0deffeccc12f.jpg)

Presbytery of Greater Atlanta - The Presbytery of Greater Atlanta is a supportive network of 100 churches and over 400 clergy with the mission of helping each to be the best it can be--to connect, equip and empower congregations and people to carry out their missions--especially those objectives particular churches cannot accomplish alone. 
![pga logo](https://cloud.githubusercontent.com/assets/15096099/12699336/96989aa2-c785-11e5-9cda-64219e491c22.png)

Convergence - The Convergence Movement is bringing together forward-thinking Catholics, Evangelicals, and mainline Protestants, along with ethnic and peace churches and other willing colleagues, in a growing movement-building collaborative. This movement connects people and organizations to solve great problems and participate in new opportunities, especially to heal the human spirit, to foster abundant life in community, to seek the common good, and to promote responsible living with the earth.

**Comment by Designer-cleonix** [comment]
Updated.
