### ISSUE TITLE
http://progress16.staging.wpengine.com/denomination/consulting-2/

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#69]
Can we add our consultant images in a square pattern and then link them to their bio pages on the Leadership Team page? 

See this page as an example: http://www.theopennetworkus.org/open-faith-conference/

Also add this video to that page: https://vimeo.com/111646273

**Comment by bikash02** [comment]
The page content is calling from a shortcode and I have to custom coded for getting the data.So need some time to fix it.
