### ISSUE TITLE
Update Ashley Harness bio

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#72]
Ashley Harness is a United Church of Christ minister and a communications strategist with a decade of experience in non-profit media work. Currently Ashley is the Director of Communications at the Center for Progressive Renewal and also a pastor at Lyndale United Church of Christ. She previously worked with Auburn’s digital organizing and media teams, providing confidential training and counsel to religious leaders seeking to use social and traditional media as a pulpit of the 21st century. Ashley first cut her media teeth at Fenton Communications, the largest public interest communications firm in the country, where she consulted for a range of non-profit organizations across issue, from international human rights to electoral political campaigns to LGBTQ equality. Ashley received her Masters of Divinity at Union Theological Seminary her Bachelor of Arts at Brown University.

**Comment by Designer-cleonix** [comment]
Updated the content. Bikash Please look after the gravity form that you have use at the end of the content.
