### ISSUE TITLE
Side Menu for http://progress16.staging.wpengine.com/denomination/keynote-speakers/

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#78]
Contact Us
Keynote Focus Areas
Reserve a Speaker

**Comment by bikash02** [comment]
updated the page side navigation 
did you create the pages?if not then please provide us the content.
1.Keynote Focus Areas
2.Reserve a Speaker

**Comment by camerontrimble** [comment]
Please create blank pages and we will add the content

**Comment by bikash02** [comment]
added the blank pages
