### ISSUE TITLE
Add instructor's image

### ISSUE THREAD

**Issue by Designer-cleonix** [ProgressiveRenewal/progress16#84]
Add instructor's image on the right bar top.
http://progress16.staging.wpengine.com/shop/online-courses/ucc-history-and-polity-spring-2016/

**Comment by bikash02** [comment]
updated.

**Comment by camerontrimble** [comment]
We need to have a thumbnail image of the instructor appear on the right side above their name on every course. This would be a template change.

**Comment by camerontrimble** [comment]
Need to be loaded on live server, make thumbnail size

**Comment by bikash02** [comment]
I have updated the code on live server.Please let me know if there is something that needed to be changed.

**Comment by camerontrimble** [comment]
Can you make images 150 x 150

**Comment by bikash02** [comment]
updated

**Comment by bikash02** [comment]
updated the images size

**Comment by camerontrimble** [comment]
These thumbnail images are distorted. What do we co about this?

http://progressiverenewal.org/shop/online-courses/radical-welcome-help-your-church-fully-embrace-the-other/

**Comment by Designer-cleonix** [comment]
I have updated the images. But please in future to maintain the aspect ratio upload instructor's images with 3:2 (width:height) ratio.
