### ISSUE TITLE
Create new super admin user

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#85]
thomas@progressiverenewal.org

**Comment by bikash02** [comment]
created the super admin user and you will get the details over the skype @debdiproy

**Comment by camerontrimble** [comment]
Need to add Thomas to the live CPR server

**Comment by camerontrimble** [comment]
I am also having trouble logging in with my credentials

**Comment by bikash02** [comment]
Thomas added to the live server with same credentials.
Note: If you are still facing this problem then please login the system using Thomas credentials and edit your profile and update your password.

Please let me know if it is not resolved.

**Comment by bikash02** [comment]
steps to follow
1.login wordpress backend
2.users -> All users -> Administrator
3. edit your profile and reset password
