### ISSUE TITLE
Get Clickdesk working

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#86]

**Comment by bikash02** [comment]
Please signup first and provide us the details.
http://progressiverenewal.org/wp-admin/admin.php?page=livily_dashboard

**Comment by bikash02** [comment]
steps to follow
1. login first http://progressiverenewal.org/wp-admin/
2.Click the link http://progressiverenewal.org/wp-admin/admin.php?page=livily_dashboard
Note: You will get the notifications to the register email id.

**Comment by thomaskleczka** [comment]
Hi Team!  I'm Thomas, a new hire at CPR.  I met Debdip yesterday, and I look forward to working with everyone!  Thanks for having me.  I am providing here the html snippet to activate click desk.  Please let me know if you need anything else!  Thanks a million.



<script type='text/javascript'>
var _glc =_glc || []; _glc.push('all_ag9zfmNsaWNrZGVza2NoYXRyDgsSBXVzZXJzGMKV4wcM');
var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' : 
'http://my.clickdesk.com/clickdesk-ui/browser/');
var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
var glcspt = document.createElement('script'); glcspt.type = 'text/javascript'; 
glcspt.async = true; glcspt.src = glcpath + 'livechat-new.js';
var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(glcspt, s);
</script>
<!— End of ClickDesk -->

**Comment by thomaskleczka** [comment]
<script type='text/javascript'>
var _glc =_glc || []; _glc.push('all_ag9zfmNsaWNrZGVza2NoYXRyDgsSBXVzZXJzGMKV4wcM');
var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' : 
'http://my.clickdesk.com/clickdesk-ui/browser/');
var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
var glcspt = document.createElement('script'); glcspt.type = 'text/javascript'; 
glcspt.async = true; glcspt.src = glcpath + 'livechat-new.js';
var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(glcspt, s);
</script>
<!— End of ClickDesk -->

**Comment by bikash02** [comment]
updated the script in your website.
