### ISSUE TITLE
Connect "Sign up" button on main page to membership product

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#88]
![screenshot 2016-02-23 14 14 00](https://cloud.githubusercontent.com/assets/15096099/13263618/4e6e46a8-da38-11e5-95bf-6e70183a55e4.png)

**Comment by bikash02** [comment]
Its already connected now in the live server but directly added to cart.
Do you want to connect the direct link?
 http://progressiverenewal.org/shop/uncategorized/unlimited-membership/ 

Please assist me if I'm wrong.
