### ISSUE TITLE
Member videos should not be visible to non-members

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#90]
We need to set this category to only show up for people who are members of the site (i.e. they have purchased a membership)

http://progressiverenewal.org/resources/

**Comment by bikash02** [comment]
I have updated the code.Kindly check with a valid user who have purchased membership.
Please let me know the status.

**Comment by camerontrimble** [comment]
The page is not showing up now. It should only be the member video icon that is invisible to non-members.

**Comment by camerontrimble** [comment]
One more fix - sorry! We need to make the member events, member spaces AND member videos only visible to the members on this page (Resources) and the Learn page.

**Comment by bikash02** [comment]
I have updated the code in Resources and Learn page.
If the member has purchased the product "Unlimited Membership" only can view the member events, member spaces and member videos.

One question:
1) What to do for the administrator login if they didn't purchase the Membership.Will they able to display the categories?

Waiting for your reply.. :)

**Comment by camerontrimble** [comment]
Admin should be able to see the videos

**Comment by bikash02** [comment]
updated..
