### ISSUE TITLE
Install Google Analytics Code

### ISSUE THREAD

**Issue by camerontrimble** [ProgressiveRenewal/progress16#98]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74411691-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by bikash02** [comment]
Please provide us ga code.

![ga](https://cloud.githubusercontent.com/assets/16361011/13397051/153d5230-df1e-11e5-9842-9a6621f613de.png)

**Comment by camerontrimble** [comment]
UA-74411691-1

**Comment by bikash02** [comment]
Added google analytics script in the website
